export const environment = {
    production: true,
    hospitalCode: 1,
    userCode: 'DAa1*',
    imgbbApi: '74aeaad1e9bebc2fbd07614debc9c4d5',
    rootApi: 'http://localhost:3000',
    authApi: 'https://digital.supersoftbd.com/HWS/Authentication',
    appointmentApi: 'https://digital.supersoftbd.com/HWS/Appointment',
    DepartmentApi: 'https://digital.supersoftbd.com/HWS/Department',
    DoctorApi: 'http://digital.supersoftbd.com/HWS/Doctor',
    AboutApi: 'https://mec.supersoftbd.com/apiA/AboutUs',
    ContactApi: 'https://mec.supersoftbd.com/apiA/Address',
    CarouselApi: 'https://mec.supersoftbd.com/apiA/Carousel',
    emptyImg: 'https://www.mykite.in/kb/NoImageFound.jpg.png',
};